import {AbsoluteFill, Img, interpolate, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import type {ResolvedAsset, Scene as SchemaScene} from '@/lib/scene-schema';
import {fontFamily} from '../../design/tokens';

export const MEMORY_LAB_EDITORIAL_VERSION = 'memory-lab-editorial@1';
type Family = 'KINETIC_CLAIM' | 'VERSION_DIFF' | 'PROCESS_MAP' | 'TIMELINE' | 'EVIDENCE_ARCHIVE' | 'CONCEPT_SPACE' | 'COMPARISON' | 'CHAPTER_INTERSTITIAL' | 'FINAL_SYNTHESIS';
type CompositionMode =
  | 'document-redline' | 'split-memory' | 'version-timeline' | 'layer-accumulation' | 'branching-versions'
  | 'typographic-contradiction' | 'phrase-correction' | 'object-led-claim' | 'editorial-statement' | 'question-field'
  | 'nested-layers' | 'continuum' | 'threshold-field' | 'source-cluster' | 'inside-outside' | 'overlap' | 'foreground-competition' | 'distance-scale'
  | 'literal-flow' | 'branch' | 'feedback-loop' | 'gate' | 'contamination-path' | 'before-after-intervention' | 'parallel-procedures' | 'progressive-accumulation' | 'failure-point'
  | 'split-screen' | 'overlay-difference' | 'before-after' | 'evidence-table' | 'two-axis' | 'paired-documents' | 'image-vs-report' | 'claim-vs-boundary' | 'condition-a-b';
type Sequence = {id: string; phase: number; view: 'establish' | 'compare' | 'conclusion' | 'spectrum'};
type MemoryLabProps = {version: typeof MEMORY_LAB_EDITORIAL_VERSION; family: Family; compositionVariant?: 0 | 1 | 2; compositionMode?: CompositionMode; backgroundMode?: 'dark' | 'light'; narrationText: string; visualThesis: string; visualLabels?: string[]; label: string; archiveDisclosure?: string; evidenceRole?: '原始研究' | '后续证据' | '解释' | '边界'; sequence?: Sequence; debugOverlay?: boolean; showSceneId?: boolean};

const palette = {bg: '#101619', panel: '#172225', panelSoft: '#213035', ink: '#f2eee6', muted: '#aeb6b3', cyan: '#79b9b4', coral: '#b96158', paper: '#e8dfcf', paperInk: '#202724', line: '#41565a'};
const chapterBackground: Record<number, string> = {1: '#0c171d', 2: '#1b1816', 3: '#1a1816', 4: '#101a20', 5: '#111a20', 6: '#121922', 7: '#121922', 8: '#111820', 9: '#1d1418', 10: '#141719'};
const safeBottom = 224;

function propsOf(scene: SchemaScene): MemoryLabProps | null {
  const raw = scene.templateProps?.memoryLab;
  if (!raw || typeof raw !== 'object') return null;
  const value = raw as Partial<MemoryLabProps>;
  if (value.version !== MEMORY_LAB_EDITORIAL_VERSION || !value.family || !value.visualThesis || !value.narrationText || !value.label) return null;
  return value as MemoryLabProps;
}
export function isMemoryLabEditorialScene(scene: SchemaScene): boolean { return propsOf(scene) !== null; }
const inAt = (progress: number, start: number, end = start + .18) => interpolate(progress, [start, end], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
const labelsFor = (data: MemoryLabProps) => data.visualLabels?.slice(0, 4) ?? [];
export const semanticStateCountForDuration = (durationSec: number) => durationSec > 13 ? 3 : durationSec >= 7 ? 2 : 1;
export const semanticStateStarts = (count: number) => count >= 3 ? [.05, .38, .7] : count === 2 ? [.07, .55] : [.08];
export const DRM_REVEAL_TIMING_V222 = {
  wordListCueStartSec: 317.438,
  wordListCueEndSec: 325.925,
  questionCueEndSec: 329.088,
  explanationCueEndSec: 331.347,
} as const;
export const OPENING_LAYOUT_V222 = {
  title: {left: 620, top: 105, width: 680, height: 90},
  cardA: {left: 155, top: 360, width: 570, height: 380},
  cardB: {left: 1195, top: 360, width: 570, height: 380},
  conflictCallout: {left: 650, top: 790, width: 620, height: 82},
} as const;
export const ARCHIVE_VISUAL_PRESENTATION_V1 = {
  S015: 'SOURCE_CHAIN_WITH_SUPPORTING_THUMBNAIL',
  S022: 'IDENTITY',
  S067: 'CONTEXT',
  S078: 'CONTEXT',
  S079: 'EDITORIAL_REPLACEMENT',
  S098: 'CONTEXT_WITH_ANNOTATION',
  S106: 'RECORD_CHAIN_WITH_SUPPORTING_DOCUMENT',
} as const;
const drmSourceWords = ['床', '休息', '清醒', '疲倦', '梦', '被子', '打盹'] as const;
export const drmVisibleTokensV222 = (sceneId: string, absoluteSec: number): string[] => {
  if (sceneId === 'S035') return [];
  if (sceneId === 'S036' || sceneId === 'S037') return [...drmSourceWords];
  if (sceneId !== 'S038') return [];
  if (absoluteSec < DRM_REVEAL_TIMING_V222.questionCueEndSec) return [...drmSourceWords, '？'];
  if (absoluteSec < DRM_REVEAL_TIMING_V222.explanationCueEndSec) return [...drmSourceWords, '睡眠？'];
  return [...drmSourceWords, '睡眠？', '原词表未出现'];
};
const semanticReveal = (progress: number, index: number, count: number) => {
  const starts = semanticStateStarts(count);
  return inAt(progress, starts[Math.min(index, starts.length - 1)]!, Math.min(.96, starts[Math.min(index, starts.length - 1)]! + .1));
};

function Meta({data, scene}: {data: MemoryLabProps; scene: SchemaScene}) {
  return <><div style={{position: 'absolute', left: 82, top: 52, color: palette.cyan, fontSize: 17, letterSpacing: 2.2}}>记忆研究 / {String(scene.chapter).padStart(2, '0')}</div>{data.evidenceRole ? <div style={{position: 'absolute', right: 82, top: 50, color: palette.muted, fontSize: 16, letterSpacing: 1.4}}>{data.evidenceRole}</div> : null}</>;
}
function Title({children, left = 120, top = 180, width = 1120, size = 78, align = 'left'}: {children: React.ReactNode; left?: number; top?: number; width?: number; size?: number; align?: 'left' | 'center' | 'right'}) {
  return <div style={{position: 'absolute', left, top, width, color: palette.ink, fontSize: size, fontWeight: 720, lineHeight: 1.1, letterSpacing: -1, textAlign: align}}>{children}</div>;
}
function Chip({children, accent = 'cyan'}: {children: React.ReactNode; accent?: 'cyan' | 'coral' | 'muted'}) {
  const color = accent === 'cyan' ? palette.cyan : accent === 'coral' ? palette.coral : palette.muted;
  return <div style={{padding: '12px 18px', border: `1px solid ${color}`, color: palette.ink, background: '#10181bcf', fontSize: 26}}>{children}</div>;
}
function SequenceSpine({sequence}: {sequence: Sequence}) {
  const worlds: Record<string, {label: string; objects: string[]}> = {
    'bartlett-to-loftus': {label: '材料 → 复述 → 措辞 → 报告', objects: ['原始材料', '改变细节', '后来报告']},
    'drm-mechanisms': {label: '词场 / 诱饵词 / 解释边界', objects: ['词表', '主旨', '细节']},
    'confidence-eyewitness': {label: '观察 → T0 → 反馈 → 保障', objects: ['初始观察', 'T0 信心', '程序保障']},
    'flashbulb-longitudinal': {label: '外部记录 → 后来版本', objects: ['T0', '鲜明感', '一致性']},
    'suggested-autobiographical': {label: '真实故事 → 建议事件 → 体验层次', objects: ['家庭材料', '访谈', '记忆体验']},
  };
  const world = worlds[sequence.id]; if (!world) return null;
  return <div style={{position: 'absolute', left: 92, right: 92, bottom: 170, display: 'flex', alignItems: 'center', gap: 24, color: palette.muted}}><div style={{fontSize: 16, letterSpacing: 2.2, color: palette.cyan}}>{world.label}</div><div style={{height: 2, flex: 1, background: palette.line}} />{world.objects.map((object, index) => <div key={object} style={{fontSize: 17, color: index === sequence.phase % world.objects.length ? palette.coral : palette.muted}}>{object}</div>)}</div>;
}

function OpeningWorld({data, progress}: {data: MemoryLabProps; progress: number}) {
  const phase = data.sequence?.phase ?? 0;
  const labels = labelsFor(data);
  const openingCard = phase === 0;
  const cardTop = openingCard ? 180 : 360;
  const cardWidth = openingCard ? 500 : 570;
  const cardHeight = openingCard ? 560 : 380;
  const stateLabel = phase === 1 ? '冲突项' : phase === 2 ? '确信' : null;
  const versionA = <div style={{position: 'absolute', left: openingCard ? 900 : OPENING_LAYOUT_V222.cardA.left, top: cardTop, width: cardWidth, height: cardHeight, padding: 42, boxSizing: 'border-box', background: palette.paper, color: palette.paperInk, rotate: openingCard ? '-2deg' : '-1deg'}}><div style={{fontSize: 20, letterSpacing: 3}}>版本 A</div><div style={{fontSize: 46, fontWeight: 730, marginTop: openingCard ? 80 : 58}}>门边 / 那句话</div><div style={{height: 4, background: palette.coral, marginTop: 34}} />{stateLabel ? <div style={{marginTop: 38, paddingTop: 18, borderTop: `2px solid ${palette.coral}`, fontSize: 24, display: 'flex', justifyContent: 'space-between'}}><span>{stateLabel}</span><span style={{color: '#8c352f'}}>{phase === 1 ? '那句话出现' : '■■■■■'}</span></div> : null}</div>;
  const versionB = <div style={{position: 'absolute', right: openingCard ? 140 : 1920 - OPENING_LAYOUT_V222.cardB.left - OPENING_LAYOUT_V222.cardB.width, top: openingCard ? 255 : cardTop, width: openingCard ? 470 : cardWidth, height: openingCard ? 500 : cardHeight, padding: 42, boxSizing: 'border-box', background: palette.panelSoft, border: `2px solid ${palette.cyan}`, rotate: openingCard ? '2deg' : '1deg', opacity: semanticReveal(progress, 0, 1)}}><div style={{fontSize: 20, letterSpacing: 3, color: palette.cyan}}>版本 B</div><div style={{fontSize: 46, fontWeight: 730, marginTop: openingCard ? 80 : 58}}>那句话没有出现</div><div style={{height: 4, background: palette.cyan, marginTop: 34}} />{stateLabel ? <div style={{marginTop: 38, paddingTop: 18, borderTop: `2px solid ${palette.cyan}`, fontSize: 24, display: 'flex', justifyContent: 'space-between'}}><span>{stateLabel}</span><span style={{color: phase === 2 ? palette.coral : palette.cyan}}>{phase === 1 ? '那句话未出现' : '■■■■■'}</span></div> : null}</div>;

  if (phase === 0) return <><Title top={145} size={72} width={700}>{data.visualThesis}</Title>{versionA}<div style={{position: 'absolute', left: 120, top: 555, width: 620, display: 'flex', gap: 18}}>{labels.map((label) => <Chip key={label}>{label}</Chip>)}</div></>;
  if (phase === 1) return <><Title top={105} size={70} width={720}>{data.visualThesis}</Title>{versionA}{versionB}<div style={{position: 'absolute', left: OPENING_LAYOUT_V222.conflictCallout.left, top: OPENING_LAYOUT_V222.conflictCallout.top, width: OPENING_LAYOUT_V222.conflictCallout.width, minHeight: OPENING_LAYOUT_V222.conflictCallout.height, padding: '18px 30px', boxSizing: 'border-box', borderTop: `3px solid ${palette.coral}`, background: palette.panel, color: palette.ink, fontSize: 28, textAlign: 'center', opacity: semanticReveal(progress, 0, 1)}}>冲突点 · 那句话是否出现</div><svg width="1920" height="1080" style={{position: 'absolute', inset: 0}}><path d="M725 740 L800 790 M1195 740 L1120 790" stroke={palette.line} strokeWidth="4" fill="none" /></svg></>;
  if (phase === 2) return <><Title left={OPENING_LAYOUT_V222.title.left} top={OPENING_LAYOUT_V222.title.top} width={OPENING_LAYOUT_V222.title.width} size={70} align="center">{data.visualThesis}</Title>{versionA}{versionB}</>;
  if (phase === 3) return <>{versionA}{versionB}<Title left={620} top={95} width={680} size={62} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', left: 750, top: 400, width: 420, display: 'grid', gap: 18}}>{['鲜明', '情绪'].map((label, index) => <div key={label} style={{padding: 24, border: `2px solid ${palette.cyan}`, textAlign: 'center', fontSize: 40, opacity: semanticReveal(progress, index, 2)}}>{label}</div>)}<div style={{padding: 25, background: '#472a2d', borderLeft: `7px solid ${palette.coral}`, fontSize: 34, opacity: semanticReveal(progress, 1, 2)}}>不是准确性凭证</div></div></>;
  if (phase === 4) return <><Title top={105} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 180, top: 410, width: 1560, height: 320, border: `2px solid ${palette.line}`}}><div style={{position: 'absolute', left: 0, top: 0, width: '64%', height: '100%', background: '#20383d', padding: 55, fontSize: 56}}>共同的大体走向<div style={{fontSize: 26, color: palette.cyan, marginTop: 85}}>仍可提供线索</div></div><div style={{position: 'absolute', right: 0, top: 0, width: '36%', height: '100%', background: '#462a2d', padding: 55, fontSize: 46, opacity: semanticReveal(progress, 0, 1)}}>细节冲突<div style={{fontSize: 26, color: palette.coral, marginTop: 85}}>仍需校验</div></div></div></>;
  if (phase === 5) return <><Title top={105} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 580, top: 300, width: 760, height: 520, border: `2px solid ${palette.line}`}}><div style={{position: 'absolute', left: 290, top: 175, width: 180, height: 150, background: palette.panelSoft, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 38}}>事件</div>{['原话', '顺序', '来源', '时间'].map((label, index) => {const positions = [[40, 40], [540, 35], [30, 370], [550, 365]]; return <div key={label} style={{position: 'absolute', left: positions[index]![0], top: positions[index]![1], width: 180, padding: 22, border: `2px solid ${index > 1 ? palette.coral : palette.cyan}`, textAlign: 'center', fontSize: 32, opacity: semanticReveal(progress, Math.min(index, 1), 2)}}>{label}</div>;})}</div></>;
  if (phase === 6) return <><div style={{position: 'absolute', left: 210, top: 250, width: 720, fontSize: 78, color: palette.muted}}>不是“记忆全是假的”</div><div style={{position: 'absolute', right: 170, bottom: 270, width: 980, padding: 60, background: '#21363b', borderLeft: `9px solid ${palette.cyan}`, fontSize: 72, fontWeight: 730, opacity: semanticReveal(progress, 0, 1)}}>而是：哪些细节需要校验？</div></>;
  if (phase === 7) return <><Title left={180} top={110} width={720} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 660, top: 260, width: 620, height: 620, borderRadius: '50%', border: `5px solid ${palette.coral}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 78, fontWeight: 760}}>确定感</div>{['错误', '回想', '准确性'].map((label, index) => <div key={label} style={{position: 'absolute', left: [230, 1320, 1330][index], top: [560, 340, 720][index], width: 300, padding: 32, borderBottom: `6px solid ${index === 2 ? palette.coral : palette.cyan}`, fontSize: 40, opacity: semanticReveal(progress, Math.min(index, 1), 2)}}>{label}</div>)}</>;
  if (phase === 8) return <><Title top={105} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 210, right: 210, top: 540, height: 8, background: palette.line}} />{['第一次', '重复讲述', '更连贯'].map((label, index) => <div key={label} style={{position: 'absolute', left: 250 + index * 580, top: 430 - index * 70, width: 360, padding: 30, background: index === 2 ? '#432a2d' : palette.panel, borderTop: `6px solid ${index === 2 ? palette.coral : palette.cyan}`, fontSize: 38, opacity: semanticReveal(progress, Math.min(index, 1), 2)}}>{label}</div>)}</>;
  if (phase === 9) return <><Title top={105} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 170, top: 510, width: 430, padding: 45, border: `2px solid ${palette.cyan}`, fontSize: 44}}>重复讲述</div><svg width="1920" height="1080" style={{position: 'absolute', inset: 0}}><path d="M600 590 C800 590 820 410 1010 410 M600 590 C800 590 820 750 1010 750" stroke={palette.line} strokeWidth="5" fill="none" /></svg><div style={{position: 'absolute', left: 1070, top: 330, width: 620, padding: 45, background: '#20383d', fontSize: 48, opacity: semanticReveal(progress, 0, 1)}}>更容易说出</div><div style={{position: 'absolute', left: 1070, top: 675, width: 620, padding: 45, background: '#472a2d', fontSize: 48, opacity: semanticReveal(progress, 0, 1)}}>≠ 更接近原事件</div></>;
  if (phase === 10) return <><Title top={105} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 270, top: 330, width: 1380, height: 470, border: `12px solid ${palette.paper}`, padding: 55}}><div style={{fontSize: 22, letterSpacing: 4, color: palette.muted}}>错误模型 / 录像</div><div style={{fontSize: 62, marginTop: 110}}>事件 → 储存 → 原样播放</div><div style={{position: 'absolute', left: 630, top: 70, width: 9, height: 330, background: palette.coral, rotate: '18deg', opacity: semanticReveal(progress, 0, 1)}} /></div></>;
  return <><div style={{position: 'absolute', left: 250, top: 170, width: 1220, height: 620, padding: 60, background: palette.paper, color: palette.paperInk, rotate: '-1deg'}}><div style={{fontSize: 28}}>回想 = <span style={{textDecoration: 'line-through', textDecorationColor: palette.coral, textDecorationThickness: 8}}>读取过去</span></div><div style={{fontSize: 70, marginTop: 135, fontWeight: 760, opacity: semanticReveal(progress, 0, 1)}}>回想 = 当前重建</div><div style={{fontSize: 30, marginTop: 95, color: '#7e302d'}}>线索 + 后来信息 + 当前理解</div></div><Title left={980} top={770} width={700} size={44} align="right">{data.visualThesis}</Title></>;
}

function DrmDemonstrationV222({data, scene, progress, absoluteSec}: {data: MemoryLabProps; scene: SchemaScene; progress: number; absoluteSec: number}) {
  const tokens = drmVisibleTokensV222(scene.id, absoluteSec);
  const sourceWords = tokens.filter((token) => drmSourceWords.includes(token as typeof drmSourceWords[number]));
  const sleepToken = tokens.find((token) => token === '睡眠？');
  const resultVisible = tokens.includes('原词表未出现');
  const positions = [[30, 35], [260, 0], [500, 50], [80, 210], [320, 185], [550, 230], [285, 355]];
  const title = scene.id === 'S036' ? data.visualThesis : scene.id === 'S037' ? '回顾原词表' : data.visualThesis;
  return <>
    <Title top={100} size={64} width={800}>{title}</Title>
    <div style={{position: 'absolute', left: 130, top: 310, width: 760, height: 510, border: `2px solid ${palette.cyan}`, background: '#17222599'}}>{sourceWords.map((word, index) => <div key={word} style={{position: 'absolute', left: positions[index]![0], top: positions[index]![1], width: 180, padding: '22px 12px', borderBottom: `4px solid ${index % 2 ? palette.cyan : palette.line}`, fontSize: 34, textAlign: 'center', opacity: scene.id === 'S036' ? semanticReveal(progress, Math.floor(index / 3), 3) : 1}}>{word}</div>)}</div>
    <div style={{position: 'absolute', right: 180, top: 350, width: 690, height: 390, border: `3px solid ${resultVisible ? palette.coral : palette.line}`, background: resultVisible ? '#482a2d' : palette.panel, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center'}}>{sleepToken ? <><div style={{fontSize: 28, color: palette.muted, marginBottom: 35}}>这个词很熟悉</div><div style={{fontSize: 68, color: resultVisible ? palette.coral : palette.ink, fontWeight: 740}}>{sleepToken}</div>{resultVisible ? <div style={{marginTop: 45, padding: '16px 24px', border: `2px solid ${palette.coral}`, color: palette.ink, fontSize: 30}}>原词表未出现</div> : null}</> : <div style={{fontSize: 96, color: palette.cyan}}>？</div>}</div>
    <div style={{position: 'absolute', left: 150, right: 150, bottom: 172, height: 3, background: `linear-gradient(90deg, ${palette.cyan}, ${resultVisible ? palette.coral : palette.line})`}} />
  </>;
}

function SequenceWorld({data, scene, progress, stateCount, absoluteSec}: {data: MemoryLabProps; scene: SchemaScene; progress: number; stateCount: number; absoluteSec: number}) {
  const sequence = data.sequence;
  if (!sequence) return null;
  const labels = labelsFor(data); const phase = sequence.phase; const reveal = (index: number) => semanticReveal(progress, index, stateCount);
  if (sequence.id === 'opening-disagreement') return <OpeningWorld data={data} progress={progress} />;
  if (sequence.id === 'drm-mechanisms' && ['S035', 'S036', 'S037', 'S038'].includes(scene.id)) return <DrmDemonstrationV222 data={data} scene={scene} progress={progress} absoluteSec={absoluteSec} />;
  if (sequence.id === 'bartlett-to-loftus' && phase < 5) return <>
    <Title top={132} size={66} width={760}>{data.visualThesis}</Title>
    <div style={{position: 'absolute', left: 850, top: 130, width: 720, height: 660, background: palette.paper, color: palette.paperInk, padding: 46, rotate: '-1deg'}}><div style={{fontSize: 18, letterSpacing: 3}}>SOURCE MATERIAL</div><div style={{marginTop: 55, fontSize: 35, lineHeight: 1.5}}>原始材料<div style={{height: 2, background: '#8c8170', margin: '24px 0'}} />复述版本<div style={{height: 2, background: palette.coral, margin: '24px 0'}} />实验措辞</div></div>
    <div style={{position: 'absolute', left: 1130, top: 360, width: 520, height: 330, background: '#111a1ddf', border: `2px solid ${palette.cyan}`, padding: 34, opacity: reveal(2)}}><div style={{fontSize: 20, color: palette.cyan}}>后来报告</div><div style={{fontSize: 38, marginTop: 70}}>{labels[phase % Math.max(1, labels.length)] ?? '改变的细节'}</div></div>
    <div style={{position: 'absolute', left: 120, top: 510, width: 600, display: 'grid', gap: 16}}>{['原始材料', '复述版本', '实验措辞', '后来报告'].map((label, index) => <div key={label} style={{height: 52, paddingLeft: 18, borderLeft: `5px solid ${index <= phase / 3 ? palette.coral : palette.line}`, color: index <= phase / 3 ? palette.ink : palette.muted, fontSize: 28}}>{label}</div>)}</div>
  </>;
  if (sequence.id === 'bartlett-to-loftus' && phase < 9) return <><Title top={120} size={66} width={820}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 150, top: 430, width: 420, height: 300, background: palette.paper, color: palette.paperInk, padding: 36, rotate: '-2deg'}}><div style={{fontSize: 20}}>原始材料</div><div style={{fontSize: 36, marginTop: 70}}>可比较的起点</div></div>{[0, 1, 2].map((index) => <div key={index} style={{position: 'absolute', left: 700 + index * 240, top: 310 + index * 130, width: 520, height: 260, padding: 35, background: index === 2 ? '#462a2d' : palette.panelSoft, borderLeft: `5px solid ${index === 2 ? palette.coral : palette.cyan}`}}><div style={{fontSize: 18, color: palette.muted}}>复述 {index + 1}</div><div style={{fontSize: 38, marginTop: 65}}>{labels[index] ?? '改变的细节'}</div></div>)}</>;
  if (sequence.id === 'bartlett-to-loftus') return <><div style={{position: 'absolute', left: 110, top: 130, width: 350, height: 230, background: palette.paper, color: palette.paperInk, padding: 28, rotate: '-2deg'}}><div style={{fontSize: 18}}>SOURCE</div><div style={{fontSize: 30, marginTop: 45}}>原始材料</div></div><Title left={520} top={120} width={1100} size={70}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 220, right: 220, top: 560, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 80}}>{['观看材料', '实验措辞', '后来报告'].map((label, index) => <div key={label} style={{padding: 40, borderBottom: `7px solid ${index === 1 ? palette.coral : palette.cyan}`, background: index === 1 ? '#482a2d' : palette.panel, fontSize: 42}}><div style={{fontSize: 18, color: palette.muted, marginBottom: 35}}>0{index + 1}</div>{labels[index] ?? label}</div>)}</div></>;
  if (sequence.id === 'drm-mechanisms' && phase < 6) return <>
    <Title top={115} size={65} width={830}>{data.visualThesis}</Title>
    <div style={{position: 'absolute', left: 860, top: 180, width: 720, height: 600}}>{['床', '梦', '夜晚', '疲倦', '枕头', '休息', '清醒', '打盹', '安静', '睡眠'].map((word, index) => {const angle = index / 10 * Math.PI * 2; const radius = word === '睡眠' ? 0 : 230 + (index % 2) * 70; return <div key={word} style={{position: 'absolute', left: 330 + Math.cos(angle) * radius, top: 250 + Math.sin(angle) * radius, color: word === '睡眠' ? palette.coral : index % 2 ? palette.muted : palette.ink, fontSize: word === '睡眠' ? 62 : 30, fontWeight: word === '睡眠' ? 760 : 520, opacity: reveal(Math.floor(index / 3))}}>{word}</div>;})}</div>
    <div style={{position: 'absolute', left: 120, top: 490, width: 600, display: 'flex', justifyContent: 'space-between'}}><div style={{width: 260, height: 210, border: `2px solid ${palette.cyan}`, padding: 28}}><div style={{color: palette.cyan, fontSize: 20}}>主旨</div><div style={{fontSize: 38, marginTop: 45}}>共同意义</div></div><div style={{width: 260, height: 210, border: `2px solid ${palette.coral}`, padding: 28}}><div style={{color: palette.coral, fontSize: 20}}>细节</div><div style={{fontSize: 38, marginTop: 45}}>是否出现</div></div></div>
  </>;
  if (sequence.id === 'drm-mechanisms' && phase < 12) return <><Title left={520} top={100} width={900} size={68} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', left: 180, top: 350, width: 700, height: 430, border: `3px solid ${palette.cyan}`, padding: 50}}><div style={{fontSize: 22, color: palette.cyan}}>主旨 GIST</div><div style={{fontSize: 62, marginTop: 100}}>共同意义</div></div><div style={{position: 'absolute', right: 180, top: 350, width: 700, height: 430, border: `3px solid ${palette.coral}`, padding: 50, textAlign: 'right'}}><div style={{fontSize: 22, color: palette.coral}}>细节 DETAIL</div><div style={{fontSize: 62, marginTop: 100}}>是否出现</div></div><div style={{position: 'absolute', left: 900, top: 520, color: palette.coral, fontSize: 88}}>≠</div></>;
  if (sequence.id === 'drm-mechanisms' && phase < 17) return <><Title top={110} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 720, top: 390, width: 480, height: 250, borderRadius: '50%', border: `4px solid ${palette.coral}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 52}}>诱饵词</div>{['主旨提取', '来源归因', '熟悉感'].map((label, index) => <div key={label} style={{position: 'absolute', left: [180, 760, 1360][index], top: [610, 730, 610][index], width: 350, padding: 38, borderTop: `6px solid ${index === 1 ? palette.coral : palette.cyan}`, background: palette.panel, textAlign: 'center', fontSize: 38}}>{labels[index] ?? label}</div>)}</>;
  if (sequence.id === 'drm-mechanisms') return <><div style={{position: 'absolute', left: 120, top: 130, display: 'flex', gap: 12}}><Chip>词表</Chip><Chip accent="coral">诱饵词</Chip></div><Title left={260} top={285} width={1400} size={86} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', left: 300, right: 300, top: 600, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 30}}>{['能解释', '需限定', '不能外推'].map((label, index) => <div key={label} style={{padding: 36, background: index === 2 ? '#482a2d' : palette.panel, borderBottom: `6px solid ${index === 2 ? palette.coral : palette.cyan}`, fontSize: 38, textAlign: 'center'}}>{labels[index] ?? label}</div>)}</div></>;
  if (sequence.id === 'confidence-eyewitness' && phase < 3) return <>
    <Title top={130} size={66} width={800}>{data.visualThesis}</Title>
    <div style={{position: 'absolute', left: 120, top: 480, width: 360, height: 230, border: `2px solid ${palette.cyan}`, padding: 28}}><div style={{fontSize: 20, color: palette.cyan}}>初始观察</div><div style={{fontSize: 38, marginTop: 55}}>现场条件</div></div>
    <div style={{position: 'absolute', left: 570, top: 530, width: 300}}><div style={{fontSize: 19, color: palette.muted}}>T0 信心</div><div style={{height: 24, marginTop: 18, background: palette.line}}><div style={{height: '100%', width: '58%', background: palette.cyan}} /></div></div>
    <div style={{position: 'absolute', left: 990, top: 380, width: 310, height: 190, borderRadius: '50%', border: `3px solid ${palette.coral}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 34}}>确认反馈</div>
    <div style={{position: 'absolute', left: 1350, top: 500, width: 360}}><div style={{fontSize: 19, color: palette.muted}}>后来信心</div><div style={{height: 24, marginTop: 18, background: palette.line}}><div style={{height: '100%', width: `${Math.min(90, 58 + phase * 4)}%`, background: palette.coral}} /></div><div style={{marginTop: 60, borderTop: `6px solid ${palette.cyan}`, paddingTop: 20, fontSize: 28}}>程序保障</div></div>
    <svg width="1920" height="1080" style={{position: 'absolute', inset: 0}}><path d="M480 595 C600 595 720 430 990 475 C1210 510 1220 610 1350 610" stroke={palette.line} strokeWidth="4" fill="none" /></svg>
  </>;
  if (sequence.id === 'confidence-eyewitness' && phase < 6) return <><Title top={115} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 240, top: 470, width: 370, padding: 42, border: `2px solid ${palette.cyan}`, fontSize: 42}}>T0 信心</div><div style={{position: 'absolute', left: 760, top: 340, width: 430, height: 430, borderRadius: '50%', border: `5px solid ${palette.coral}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 46}}>确认反馈</div><div style={{position: 'absolute', right: 220, top: 540, width: 400}}><div style={{fontSize: 24}}>后来信心</div><div style={{height: 28, marginTop: 30, background: palette.line}}><div style={{height: '100%', width: '86%', background: palette.coral}} /></div></div><svg width="1920" height="1080" style={{position: 'absolute', inset: 0}}><path d="M610 540 C700 540 700 540 760 540 M1190 540 C1320 540 1320 620 1380 620" stroke={palette.line} strokeWidth="5" fill="none" /></svg></>;
  if (sequence.id === 'confidence-eyewitness') return <><Title left={340} top={140} width={1240} size={76} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', left: 220, right: 220, top: 460, height: 330, border: `3px solid ${palette.cyan}`, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)'}}>{['先记录', '隔离反馈', '保存程序'].map((label, index) => <div key={label} style={{padding: 55, borderRight: index < 2 ? `1px solid ${palette.line}` : 'none', fontSize: 42, textAlign: 'center'}}><div style={{fontSize: 20, color: index === 1 ? palette.coral : palette.cyan, marginBottom: 75}}>保障 {index + 1}</div>{labels[index] ?? label}</div>)}</div></>;
  if (sequence.id === 'flashbulb-longitudinal' && phase < 3) return <>
    <Title top={125} size={66} width={760}>{data.visualThesis}</Title>
    <div style={{position: 'absolute', left: 110, top: 480, width: 430, height: 250, background: palette.paper, color: palette.paperInk, padding: 30, rotate: '-2deg'}}><div style={{fontSize: 18, letterSpacing: 3}}>T0 外部记录</div><div style={{fontSize: 34, marginTop: 55}}>事件后的原始版本</div></div>
    <div style={{position: 'absolute', left: 680, top: 310, width: 880, height: 460}}>{[0, 1, 2].map((index) => <div key={index} style={{position: 'absolute', left: index * 170, top: index * 75, width: 540, height: 270, padding: 28, background: index === 0 ? '#1c2d31' : index === 1 ? '#2a2525' : '#24272a', borderLeft: `5px solid ${index === 2 ? palette.coral : palette.cyan}`, opacity: reveal(index)}}><div style={{fontSize: 19, color: palette.muted}}>后来报告 {index + 1}</div><div style={{fontSize: 34, marginTop: 65}}>{labels[index] ?? ['一致性', '鲜明感', '信心'][index]}</div></div>)}</div>
    <div style={{position: 'absolute', right: 100, bottom: 190, width: 480, display: 'flex', gap: 16}}>{['一致性', '鲜明感', '信心'].map((label, index) => <div key={label} title={label} style={{flex: 1, height: 14 + index * 12, background: index === 1 ? palette.coral : palette.cyan}} />)}</div>
  </>;
  if (sequence.id === 'flashbulb-longitudinal' && phase < 8) return <><Title top={115} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 120, top: 520, width: 360, height: 230, background: palette.paper, color: palette.paperInk, padding: 32, rotate: '-2deg'}}><div style={{fontSize: 18}}>T0</div><div style={{fontSize: 32, marginTop: 55}}>外部记录</div></div>{[0, 1, 2].map((index) => <div key={index} style={{position: 'absolute', left: 650 + index * 260, top: 330 + index * 130, width: 520, height: 260, background: index === 2 ? '#482a2d' : palette.panelSoft, borderLeft: `6px solid ${index === 2 ? palette.coral : palette.cyan}`, padding: 38}}><div style={{fontSize: 19, color: palette.muted}}>后来报告 {index + 1}</div><div style={{fontSize: 38, marginTop: 60}}>{labels[index] ?? '版本细节'}</div></div>)}</>;
  if (sequence.id === 'flashbulb-longitudinal') return <><div style={{position: 'absolute', left: 120, top: 120, width: 300, height: 190, background: palette.paper, color: palette.paperInk, padding: 28, rotate: '-2deg'}}>T0 外部记录</div><Title left={470} top={120} width={1200} size={70}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 240, right: 240, top: 480, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 30}}>{['一致性', '鲜明感', '信心'].map((label, index) => <div key={label} style={{height: 290, padding: 40, borderBottom: `12px solid ${index === 1 ? palette.coral : palette.cyan}`, background: palette.panel, fontSize: 44, textAlign: 'center'}}><div style={{fontSize: 20, color: palette.muted, marginBottom: 65}}>指标</div>{labels[index] ?? label}</div>)}</div></>;
  if (phase < 4) return <>
    <Title top={120} size={64} width={760}>{data.visualThesis}</Title>
    <div style={{position: 'absolute', left: 105, top: 500, width: 530, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14}}>{['真实故事', '家庭材料', '建议事件', '重复访谈'].map((label, index) => <div key={label} style={{padding: 24, background: index === 2 ? '#48282d' : palette.panel, border: `1px solid ${index === 2 ? palette.coral : palette.line}`, fontSize: 28, opacity: reveal(index)}}>{label}</div>)}</div>
    <div style={{position: 'absolute', left: 760, top: 250, width: 830, height: 500}}><div style={{position: 'absolute', left: 0, right: 0, top: 230, height: 8, background: `linear-gradient(90deg, ${palette.line}, ${palette.cyan}, ${palette.coral})`}} />{['配合', '相信', '意象', '部分回忆', '完整记忆'].map((label, index) => <div key={label} style={{position: 'absolute', left: index * 175, top: 155 + (index % 2) * 150, width: 150, textAlign: 'center', color: index <= phase / 3 ? palette.ink : palette.muted, fontSize: 28, opacity: reveal(index)}}><div style={{width: 22, height: 22, borderRadius: '50%', background: index <= phase / 3 ? palette.coral : palette.line, margin: '0 auto 22px'}} />{label}</div>)}</div>
  </>;
  if (phase < 7) return <><Title top={115} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 160, top: 390, width: 430, height: 330, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12}}>{['真实故事', '家庭材料', '建议事件', '重复访谈'].map((label, index) => <div key={label} style={{padding: 25, background: index === 2 ? '#48282d' : palette.panel, border: `1px solid ${index === 2 ? palette.coral : palette.line}`, fontSize: 27}}>{label}</div>)}</div><div style={{position: 'absolute', left: 790, top: 330, width: 760, height: 470, borderRadius: '50%', border: `5px solid ${palette.cyan}`, display: 'flex', alignItems: 'center', justifyContent: 'center'}}><div style={{fontSize: 56}}>访谈 × {Math.min(3, phase - 2)}</div><div style={{position: 'absolute', right: -90, bottom: 30, padding: 38, background: '#472a2d', borderLeft: `6px solid ${palette.coral}`, fontSize: 38}}>{labels[phase % Math.max(1, labels.length)] ?? '体验报告'}</div></div></>;
  if (phase < 9) return <><Title left={470} top={110} width={980} size={70} align="center">{data.visualThesis}</Title>{['实验配合', '相信发生', '出现意象'].map((label, index) => <div key={label} style={{position: 'absolute', left: 250 + index * 470, top: 400 + index * 110, width: 520, height: 260, padding: 42, background: index === 2 ? '#482a2e' : palette.panelSoft, borderLeft: `6px solid ${index === 2 ? palette.coral : palette.cyan}`, fontSize: 44}}><div style={{fontSize: 19, color: palette.muted, marginBottom: 55}}>体验层 {index + 1}</div>{labels[index] ?? label}</div>)}</>;
  return <><div style={{position: 'absolute', left: 105, top: 170, width: 430, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12}}>{['真实故事', '建议事件', '访谈', '报告'].map((label, index) => <div key={label} style={{padding: 22, background: index === 1 ? '#48282d' : palette.panel, fontSize: 25}}>{label}</div>)}</div><Title left={650} top={110} width={1050} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 600, top: 420, width: 1050, height: 360}}><div style={{position: 'absolute', left: 0, right: 0, top: 165, height: 10, background: `linear-gradient(90deg, ${palette.line}, ${palette.cyan}, ${palette.coral})`}} />{['配合', '相信', '意象', '部分回忆', '完整记忆'].map((label, index) => <div key={label} style={{position: 'absolute', left: index * 220, top: index % 2 ? 210 : 85, width: 170, textAlign: 'center', fontSize: 27}}><div style={{width: 24, height: 24, borderRadius: '50%', background: index < 3 ? palette.cyan : palette.coral, margin: '0 auto 22px'}} />{label}</div>)}</div></>;
}

function KineticClaim({data, progress, stateCount}: {data: MemoryLabProps; progress: number; stateCount: number}) {
  const labels = labelsFor(data); const mode = data.compositionMode ?? 'editorial-statement';
  if (mode === 'typographic-contradiction') return <><div style={{position: 'absolute', inset: '180px 120px 240px', display: 'grid', gridTemplateColumns: '1fr 180px 1fr', alignItems: 'center'}}><div style={{fontSize: 96, fontWeight: 760, textAlign: 'right', opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0] ?? data.visualThesis}</div><div style={{fontSize: 120, color: palette.coral, textAlign: 'center', opacity: semanticReveal(progress, 1, stateCount)}}>≠</div><div style={{fontSize: 96, fontWeight: 760, opacity: semanticReveal(progress, 1, stateCount)}}>{labels[1] ?? '准确'}</div></div><Title left={420} top={720} width={1080} size={42} align="center">{data.visualThesis}</Title></>;
  if (mode === 'phrase-correction') return <><div style={{position: 'absolute', left: 180, top: 280, width: 1300, fontSize: 70, color: palette.muted}}>“{labels[0] ?? '原命题'}”<div style={{height: 8, background: palette.coral, width: `${inAt(progress, .2) * 100}%`, translate: '0 -44px', rotate: '-2deg'}} /></div><div style={{position: 'absolute', left: 450, top: 540, width: 1260, fontSize: 78, fontWeight: 740, color: palette.ink}}>→ {data.visualThesis}</div></>;
  if (mode === 'question-field') return <><div style={{position: 'absolute', left: 170, top: 170, width: 720, height: 620, borderRadius: '50%', border: `2px solid ${palette.cyan}`, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 70, fontSize: 82, fontWeight: 740, textAlign: 'center'}}>{data.visualThesis}</div><div style={{position: 'absolute', right: 170, top: 285, display: 'grid', gap: 28}}>{labels.map((label, index) => <div key={label} style={{opacity: semanticReveal(progress, index, stateCount)}}><Chip accent={index === 1 ? 'coral' : 'cyan'}>{label}</Chip></div>)}</div></>;
  if (mode === 'object-led-claim') return <><div style={{position: 'absolute', left: 140, top: 250, width: 660, height: 500, background: palette.paper, color: palette.paperInk, padding: 45, rotate: '-2deg'}}>{labels.map((label, index) => <div key={label} style={{fontSize: 36, padding: '22px 0', borderBottom: '1px solid #8f8778', opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</div><Title left={930} top={330} width={760} size={78}>{data.visualThesis}</Title></>;
  return <><Title left={260} top={285} width={1400} size={110} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', left: 430, right: 430, top: 620, display: 'flex', justifyContent: 'center', gap: 26}}>{labels.map((label, index) => <div key={label} style={{opacity: semanticReveal(progress, index, stateCount)}}><Chip accent={index === 1 ? 'coral' : 'cyan'}>{label}</Chip></div>)}</div></>;
}

function VersionDiff({data, progress, stateCount}: {data: MemoryLabProps; progress: number; stateCount: number}) {
  const labels = labelsFor(data); const mode = data.compositionMode ?? 'document-redline';
  if (mode === 'split-memory') return <><div style={{position: 'absolute', inset: '145px 90px 190px', display: 'grid', gridTemplateColumns: '1fr 140px 1fr'}}><div style={{background: '#d9dfd8', color: palette.paperInk, padding: 52, opacity: semanticReveal(progress, 0, stateCount)}}><div style={{fontSize: 22}}>版本 A</div><div style={{fontSize: 58, marginTop: 120}}>{labels[0] ?? '原记录'}</div></div><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 72, color: palette.coral, opacity: semanticReveal(progress, 1, stateCount)}}>≠</div><div style={{background: palette.panelSoft, padding: 52, opacity: semanticReveal(progress, 1, stateCount)}}><div style={{fontSize: 22, color: palette.cyan}}>版本 B</div><div style={{fontSize: 58, marginTop: 120}}>{labels[1] ?? '当前回想'}</div></div></div><Title left={460} top={760} width={1000} size={42} align="center">{data.visualThesis}</Title></>;
  if (mode === 'version-timeline') return <><Title top={110} size={70}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 190, right: 190, top: 650, height: 6, background: palette.line}} />{['T0', '后来报告', '当前版本'].map((label, index) => <div key={label} style={{position: 'absolute', left: 170 + index * 560, top: 390 + index * 55, width: 480, minHeight: 240, padding: 42, background: index === 2 ? '#472a2d' : palette.panelSoft, borderTop: `7px solid ${index === 2 ? palette.coral : palette.cyan}`, fontSize: 42, opacity: semanticReveal(progress, index, stateCount)}}><div style={{fontSize: 20, color: palette.muted, marginBottom: 55}}>{label}</div>{labels[index] ?? label}</div>)}</>;
  if (mode === 'layer-accumulation') return <><Title left={115} top={120} width={720} size={65}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 810, top: 160, width: 820, height: 610}}>{['原始痕迹', '后来信息', '当前推断'].map((label, index) => <div key={label} style={{position: 'absolute', left: index * 100, top: index * 110, width: 600, height: 300, background: index === 0 ? '#dfe1d8' : index === 1 ? '#244148dd' : '#492a2ddd', color: index === 0 ? palette.paperInk : palette.ink, padding: 38, border: `2px solid ${index === 2 ? palette.coral : palette.cyan}`, opacity: semanticReveal(progress, index, stateCount)}}><div style={{fontSize: 24}}>{label}</div><div style={{fontSize: 42, marginTop: 75}}>{labels[index] ?? label}</div></div>)}</div></>;
  if (mode === 'branching-versions') return <><Title top={125} size={70}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 170, top: 510, width: 360, padding: 35, border: `2px solid ${palette.cyan}`, fontSize: 36}}>同一起点</div><svg width="1920" height="1080" style={{position: 'absolute', inset: 0}}><path d="M530 565 C760 565 760 390 980 390 M530 565 C760 565 760 725 980 725" stroke={palette.line} strokeWidth="5" fill="none" /></svg>{labels.slice(0, 2).map((label, index) => <div key={label} style={{position: 'absolute', left: 1030, top: index ? 650 : 315, width: 600, padding: 42, background: index ? '#44282b' : palette.panelSoft, fontSize: 48, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</>;
  return <><div style={{position: 'absolute', left: 250, top: 170, width: 1220, height: 620, padding: 60, background: palette.paper, color: palette.paperInk, rotate: '-1deg'}}><div style={{fontSize: 30}}>原始措辞</div><div style={{fontSize: 58, marginTop: 90, opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0] ?? '原版本'} <span style={{textDecoration: 'line-through', textDecorationColor: palette.coral, textDecorationThickness: 8}}>{labels[1] ?? '旧细节'}</span></div><div style={{fontSize: 58, marginTop: 75, color: '#7e302d', opacity: semanticReveal(progress, 1, stateCount)}}>＋ {labels[2] ?? '后来措辞'}</div></div><Title left={1040} top={700} width={650} size={48} align="right">{data.visualThesis}</Title></>;
}

function ConceptSpace({data, progress, stateCount}: {data: MemoryLabProps; progress: number; stateCount: number}) {
  const labels = labelsFor(data); const mode = data.compositionMode ?? 'source-cluster';
  if (mode === 'nested-layers') return <><Title top={120} size={68}>{data.visualThesis}</Title>{labels.map((label, index) => <div key={label} style={{position: 'absolute', left: 380 + index * 120, top: 380 + index * 75, width: 980 - index * 240, height: 430 - index * 125, border: `3px solid ${index === labels.length - 1 ? palette.coral : palette.cyan}`, display: 'flex', alignItems: 'flex-start', justifyContent: 'flex-end', padding: 22, fontSize: 29, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</>;
  if (mode === 'continuum' || mode === 'distance-scale') return <><Title top={100} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 190, right: 190, top: 655, height: 16, background: `linear-gradient(90deg, ${palette.cyan}, ${palette.line}, ${palette.coral})`}} />{labels.map((label, index) => <div key={label} style={{position: 'absolute', left: 150 + index * 570, top: 390 + (index % 2) * 80, width: 480, minHeight: 220, padding: 42, background: index === 2 ? '#472a2d' : palette.panelSoft, borderTop: `7px solid ${index === 2 ? palette.coral : palette.cyan}`, fontSize: 44, textAlign: 'center', opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</>;
  if (mode === 'threshold-field' || mode === 'inside-outside') return <><Title top={120} size={68}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 250, top: 390, width: 1320, height: 380, border: `3px solid ${palette.cyan}`, background: `linear-gradient(90deg, transparent 0 55%, #512d3155 55%)`}}><div style={{position: 'absolute', left: '55%', top: 0, bottom: 0, width: 4, background: palette.coral}} />{labels.map((label, index) => <div key={label} style={{position: 'absolute', left: 120 + index * 430, top: 150 + (index % 2) * 80, fontSize: 35, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</div></>;
  if (mode === 'overlap') return <><Title top={110} size={68}>{data.visualThesis}</Title>{labels.slice(0, 3).map((label, index) => <div key={label} style={{position: 'absolute', left: 420 + index * 330, top: 410 + (index % 2) * 100, width: 460, height: 310, borderRadius: '50%', border: `3px solid ${index === 1 ? palette.coral : palette.cyan}`, background: index === 1 ? '#572e3233' : '#3151572b', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 35, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</>;
  if (mode === 'foreground-competition') return <><Title top={110} size={68}>{data.visualThesis}</Title>{labels.map((label, index) => <div key={label} style={{position: 'absolute', left: 230 + index * 330, top: 420 + index * 75, width: 650, height: 210, background: index === 0 ? '#274148' : index === 1 ? '#4b2a2f' : palette.panelSoft, borderLeft: `8px solid ${index === 1 ? palette.coral : palette.cyan}`, padding: 42, fontSize: 44, zIndex: labels.length - index, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</>;
  return <><Title left={600} top={100} width={720} size={68} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', left: 310, top: 390, width: 1300, height: 430}}>{labels.map((label, index) => {const positions = [[0, 150], [420, 0], [880, 180], [480, 300]]; return <div key={label} style={{position: 'absolute', left: positions[index]![0], top: positions[index]![1], width: 290, minHeight: 120, border: `2px solid ${index === 1 ? palette.coral : palette.cyan}`, background: palette.panel, padding: 28, fontSize: 34, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>;})}</div></>;
}

function ProcessMap({data, progress, stateCount}: {data: MemoryLabProps; progress: number; stateCount: number}) {
  const labels = labelsFor(data); const mode = data.compositionMode ?? 'literal-flow';
  if (mode === 'feedback-loop') return <><Title top={115} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 600, top: 350, width: 720, height: 420, borderRadius: '50%', border: `5px solid ${palette.cyan}`}} />{labels.slice(0, 3).map((label, index) => <div key={label} style={{position: 'absolute', left: [420, 820, 1260][index], top: [500, 690, 500][index], width: 260, padding: 30, background: index === 1 ? '#482b2e' : palette.panel, fontSize: 34, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</>;
  if (mode === 'gate' || mode === 'failure-point') return <><Title top={115} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 180, top: 530, width: 430, padding: 38, border: `2px solid ${palette.cyan}`, fontSize: 40, opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0] ?? '输入'}</div><div style={{position: 'absolute', left: 820, top: 360, width: 110, height: 430, background: mode === 'failure-point' ? palette.coral : palette.cyan, opacity: semanticReveal(progress, 1, stateCount)}}><div style={{rotate: '-90deg', translate: '-125px 175px', width: 360, color: palette.bg, fontSize: 28, fontWeight: 760, textAlign: 'center'}}>{mode === 'failure-point' ? '风险点' : '程序门'}</div></div><div style={{position: 'absolute', right: 180, top: 530, width: 520, padding: 38, background: palette.panelSoft, fontSize: 40, opacity: semanticReveal(progress, 2, stateCount)}}>{labels[2] ?? '保留记录'}</div></>;
  if (mode === 'contamination-path') return <><Title top={110} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 170, top: 490, width: 430, padding: 38, border: `2px solid ${palette.cyan}`, fontSize: 38, opacity: semanticReveal(progress, 0, stateCount)}}>原始信息</div><div style={{position: 'absolute', left: 720, top: 350, width: 390, height: 390, borderRadius: '50%', border: `4px solid ${palette.coral}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 38, opacity: semanticReveal(progress, 1, stateCount)}}>暗示进入</div><div style={{position: 'absolute', right: 150, top: 565, width: 470, padding: 38, background: '#472a2d', fontSize: 38, opacity: semanticReveal(progress, 2, stateCount)}}>新版本报告</div><svg width="1920" height="1080" style={{position: 'absolute', inset: 0}}><path d="M600 550 L720 550 M1110 550 C1260 550 1280 640 1370 640" stroke={palette.line} strokeWidth="5" fill="none" /></svg></>;
  if (mode === 'branch' || mode === 'parallel-procedures') return <><Title top={110} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 170, top: 510, width: 360, padding: 38, border: `2px solid ${palette.cyan}`, fontSize: 38, opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0] ?? '起点'}</div><svg width="1920" height="1080" style={{position: 'absolute', inset: 0}}><path d="M530 570 C760 570 780 390 980 390 M530 570 C760 570 780 735 980 735" stroke={palette.line} strokeWidth="5" fill="none" /></svg>{labels.slice(1, 3).map((label, index) => <div key={label} style={{position: 'absolute', left: 1040, top: index ? 650 : 310, width: 540, padding: 42, background: index ? '#462b2e' : palette.panelSoft, fontSize: 42, opacity: semanticReveal(progress, index + 1, stateCount)}}>{label}</div>)}</>;
  if (mode === 'progressive-accumulation') return <><Title top={110} size={66}>{data.visualThesis}</Title>{labels.map((label, index) => <div key={label} style={{position: 'absolute', left: 210 + index * 430, top: 650 - index * 125, width: 380, height: 130 + index * 125, background: index === labels.length - 1 ? '#482a2e' : palette.panelSoft, borderTop: `5px solid ${index === labels.length - 1 ? palette.coral : palette.cyan}`, padding: 30, fontSize: 38, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</>;
  if (mode === 'before-after-intervention') return <><Title top={105} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 140, top: 420, width: 540, height: 300, padding: 42, background: palette.panel, borderTop: `5px solid ${palette.cyan}`, fontSize: 44, opacity: semanticReveal(progress, 0, stateCount)}}>之前<br /><span style={{fontSize: 30, color: palette.muted}}>{labels[0]}</span></div><div style={{position: 'absolute', left: 765, top: 360, width: 390, height: 390, borderRadius: '50%', border: `4px solid ${palette.coral}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 36, opacity: semanticReveal(progress, 1, stateCount)}}>{labels[1] ?? '干预'}</div><div style={{position: 'absolute', right: 140, top: 420, width: 540, height: 300, padding: 42, background: '#41292c', borderTop: `5px solid ${palette.coral}`, fontSize: 44, opacity: semanticReveal(progress, 2, stateCount)}}>之后<br /><span style={{fontSize: 30, color: palette.muted}}>{labels[2]}</span></div></>;
  return <><Title top={110} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 150, right: 150, top: 500, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 100}}>{labels.slice(0, 3).map((label, index) => <div key={label} style={{minHeight: 190, padding: 40, background: index === 1 ? '#472a2e' : palette.panel, borderBottom: `6px solid ${index === 1 ? palette.coral : palette.cyan}`, fontSize: 42, opacity: semanticReveal(progress, index, stateCount)}}><div style={{fontSize: 19, color: palette.muted, marginBottom: 40}}>0{index + 1}</div>{label}</div>)}</div></>;
}

function Comparison({data, progress, stateCount}: {data: MemoryLabProps; progress: number; stateCount: number}) {
  const labels = labelsFor(data); const mode = data.compositionMode ?? 'split-screen';
  if (mode === 'overlay-difference') return <><Title top={105} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 350, top: 380, width: 900, height: 370, background: '#234047cc', padding: 55, fontSize: 48, opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0] ?? 'A'}</div><div style={{position: 'absolute', left: 700, top: 500, width: 900, height: 330, background: '#512b30d9', padding: 55, textAlign: 'right', fontSize: 48, opacity: semanticReveal(progress, 1, stateCount)}}>{labels[1] ?? 'B'}</div></>;
  if (mode === 'two-axis') return <><Title top={90} size={64}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 440, top: 300, width: 1040, height: 560, borderLeft: `5px solid ${palette.cyan}`, borderBottom: `5px solid ${palette.cyan}`, background: '#17222588'}}><div style={{position: 'absolute', left: -300, top: 160, width: 250, padding: 32, background: palette.panelSoft, fontSize: 40, opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0]}</div><div style={{position: 'absolute', right: 0, bottom: -110, width: 330, padding: 32, background: palette.panelSoft, fontSize: 40, opacity: semanticReveal(progress, 1, stateCount)}}>{labels[1]}</div><div style={{position: 'absolute', left: 560, top: 90, width: 280, height: 280, borderRadius: '50%', background: palette.coral, opacity: semanticReveal(progress, 1, stateCount), display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 38}}>{labels[2] ?? '对照'}</div></div></>;
  if (mode === 'evidence-table') return <><Title top={95} size={62}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 180, right: 180, top: 390, borderTop: `4px solid ${palette.cyan}`}}>{['可观察', '能推出', '不能推出'].map((heading, index) => <div key={heading} style={{display: 'grid', gridTemplateColumns: '320px 1fr', minHeight: 115, borderBottom: `1px solid ${palette.line}`, alignItems: 'center', fontSize: 31, opacity: semanticReveal(progress, index, stateCount)}}><div style={{color: index === 2 ? palette.coral : palette.cyan}}>{heading}</div><div>{labels[index] ?? data.visualThesis}</div></div>)}</div></>;
  if (mode === 'paired-documents') return <><Title top={100} size={62}>{data.visualThesis}</Title>{labels.slice(0, 2).map((label, index) => <div key={label} style={{position: 'absolute', left: 250 + index * 750, top: 390 + index * 80, width: 620, height: 390, background: index ? palette.panelSoft : palette.paper, color: index ? palette.ink : palette.paperInk, padding: 50, rotate: index ? '2deg' : '-2deg', fontSize: 48, opacity: semanticReveal(progress, index, stateCount)}}><div style={{fontSize: 19, letterSpacing: 3, marginBottom: 95}}>DOCUMENT {index + 1}</div>{label}</div>)}</>;
  if (mode === 'claim-vs-boundary') return <><div style={{position: 'absolute', left: 130, top: 220, width: 1000, fontSize: 78, fontWeight: 740, opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0] ?? data.visualThesis}</div><div style={{position: 'absolute', right: 130, bottom: 240, width: 950, padding: 55, background: '#48292d', borderLeft: `8px solid ${palette.coral}`, fontSize: 58, textAlign: 'right', opacity: semanticReveal(progress, 1, stateCount)}}>{labels[1] ?? '结论边界'}</div><div style={{position: 'absolute', left: 130, right: 130, top: 535, height: 4, background: palette.line}} /></>;
  if (mode === 'condition-a-b' || mode === 'before-after' || mode === 'image-vs-report') return <><Title left={610} top={95} width={700} size={60} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', inset: '310px 100px 210px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 28}}><div style={{background: palette.panel, borderTop: `7px solid ${palette.cyan}`, padding: 55, fontSize: 52, opacity: semanticReveal(progress, 0, stateCount)}}><div style={{fontSize: 20, color: palette.muted, marginBottom: 80}}>条件 A</div>{labels[0]}</div><div style={{background: '#3d292c', borderTop: `7px solid ${palette.coral}`, padding: 55, textAlign: 'right', fontSize: 52, opacity: semanticReveal(progress, 1, stateCount)}}><div style={{fontSize: 20, color: palette.muted, marginBottom: 80}}>条件 B</div>{labels[1]}</div></div></>;
  return <><div style={{position: 'absolute', inset: '140px 0 190px', display: 'grid', gridTemplateColumns: '1fr 1fr'}}><div style={{background: '#18272b', padding: '120px 110px', fontSize: 58, opacity: semanticReveal(progress, 0, stateCount)}}>{labels[0] ?? '一侧'}</div><div style={{background: '#241c1e', padding: '350px 110px 80px', textAlign: 'right', fontSize: 58, opacity: semanticReveal(progress, 1, stateCount)}}>{labels[1] ?? '另一侧'}</div></div><Title left={560} top={145} width={800} size={70} align="center">{data.visualThesis}</Title></>;
}

function Timeline({data, progress, stateCount}: {data: MemoryLabProps; progress: number; stateCount: number}) {const labels = labelsFor(data); return <><Title top={110} size={66}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 180, right: 180, top: 650, height: 5, background: palette.line}} />{labels.map((label, index) => <div key={label} style={{position: 'absolute', left: 170 + index * 560, top: 390 + (index % 2) * 90, width: 470, minHeight: 230, padding: 40, background: index === (data.sequence?.phase ?? 0) % Math.max(1, labels.length) ? '#472a2d' : palette.panelSoft, borderTop: `7px solid ${index === (data.sequence?.phase ?? 0) % Math.max(1, labels.length) ? palette.coral : palette.cyan}`, fontSize: 42, opacity: semanticReveal(progress, index, stateCount)}}><div style={{fontSize: 20, color: palette.muted, marginBottom: 55}}>时间点 {index + 1}</div>{label}</div>)}</>;}
function EvidenceArchive({data, scene, progress, asset}: {data: MemoryLabProps; scene: SchemaScene; progress: number; asset?: ResolvedAsset}) {
  if (asset?.mediaType !== 'image') throw new Error('EVIDENCE_ARCHIVE requires an exact bound image asset');
  if (scene.id === 'S015') return <>
    <Title top={105} width={1180} size={66}>{data.visualThesis}</Title>
    <div style={{position: 'absolute', left: 125, top: 345, width: 1230, display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 28}}>{['Kathlamet\n文本传统', '故事材料', '跨文化复述', 'Bartlett\n实验'].map((label, index) => <div key={label} style={{position: 'relative', minHeight: 210, padding: '46px 28px', boxSizing: 'border-box', whiteSpace: 'pre-line', background: index === 3 ? '#472a2e' : palette.panel, borderTop: `6px solid ${index === 3 ? palette.coral : palette.cyan}`, fontSize: 38, opacity: semanticReveal(progress, index, 3)}}>{label}{index < 3 ? <div style={{position: 'absolute', right: -25, top: 75, color: palette.muted, fontSize: 36}}>→</div> : null}</div>)}</div>
    <div style={{position: 'absolute', right: 92, top: 250, width: 330, height: 470, overflow: 'hidden', border: `2px solid ${palette.line}`, opacity: .72}}><Img src={staticFile(asset.publicPath)} style={{width: '100%', height: '100%', objectFit: 'cover', filter: 'contrast(.92) saturate(.65)'}} /></div>
    <div style={{position: 'absolute', left: 125, top: 660, width: 1120, padding: '18px 22px', background: '#172225e8', borderLeft: `5px solid ${palette.cyan}`, fontSize: 26, fontWeight: 650}}>来源卷 · 不是《幽灵之战》的故事原页</div>
    <div style={{position: 'absolute', left: 125, top: 738, width: 1120, color: palette.muted, fontSize: 18}}>{asset.attribution || 'Franz Boas · Public domain'}</div>
  </>;
  if (scene.id === 'S106') return <>
    <Title top={105} width={1050} size={66}>{data.visualThesis}</Title>
    <div style={{position: 'absolute', left: 125, top: 350, width: 930, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 24}}>{['尽早写下', '保留时间戳', '保护原始版本'].map((label, index) => <div key={label} style={{minHeight: 180, padding: '48px 30px', background: index === 2 ? '#472a2e' : palette.panel, borderTop: `6px solid ${index === 2 ? palette.coral : palette.cyan}`, fontSize: 35, opacity: semanticReveal(progress, index, 3)}}>{label}</div>)}</div>
    <div style={{position: 'absolute', right: 110, top: 185, width: 690, height: 585, overflow: 'hidden', border: `2px solid ${palette.line}`}}><Img src={staticFile(asset.publicPath)} style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 28%', filter: 'contrast(.96) saturate(.55)'}} /></div>
    <div style={{position: 'absolute', left: 125, top: 625, width: 930, padding: '18px 22px', background: '#172225e8', borderLeft: `5px solid ${palette.cyan}`, fontSize: 25, fontWeight: 650}}>1880–1893 讲义笔记 · 展示“有时间范围的书面痕迹”</div>
    <div style={{position: 'absolute', left: 125, top: 708, width: 930, color: palette.muted, fontSize: 18}}>Grace Julian Clarke / Indiana State Library · 公版 · 非具体案件证据</div>
  </>;
  return <><Img src={staticFile(asset.publicPath)} style={{position: 'absolute', left: 620, top: 70, width: 1250, height: 850, objectFit: 'cover', scale: interpolate(progress, [0, .35, .7, 1], [1.02, 1.12, 1.12, 1.03]), filter: 'contrast(.92) saturate(.72)'}} /><div style={{position: 'absolute', inset: 0, background: 'linear-gradient(90deg, #101619 0 33%, #101619dc 37%, transparent 72%)'}} /><Title top={210} width={660} size={70}>{data.visualThesis}</Title><div style={{position: 'absolute', left: 120, top: 590, width: 620, padding: '14px 18px', color: palette.ink, background: '#172225e8', borderLeft: `5px solid ${palette.cyan}`, fontSize: 25, fontWeight: 650, opacity: semanticReveal(progress, 1, 3)}}>{data.archiveDisclosure || '原始资料'}</div><div style={{position: 'absolute', left: 120, top: 670, width: 620, color: palette.muted, fontSize: 18, opacity: semanticReveal(progress, 2, 3)}}>{asset.attribution || labelsFor(data).join(' · ')}</div></>;
}
function ChapterInterstitial({data, scene, progress}: {data: MemoryLabProps; scene: SchemaScene; progress: number}) {
  const boundarySteps = ['彼此竞争', '可能共同作用', '不是已证实因果链'];
  return <><div style={{position: 'absolute', left: 150, top: 170, color: palette.cyan, fontSize: 42}}>第 {String(scene.chapter).padStart(2, '0')} 章</div><div style={{opacity: semanticReveal(progress, 1, 2)}}><Title left={420} top={235} width={1250} size={100}>{data.visualThesis}</Title></div><div style={{position: 'absolute', left: 150, top: 555, display: 'flex', gap: 28}}>{boundarySteps.map((label, index) => <div key={label} style={{width: 410, minHeight: 150, padding: '30px 34px', boxSizing: 'border-box', border: `2px solid ${index === 2 ? palette.coral : palette.cyan}`, background: index === 2 ? '#d66b5d24' : '#77a9a51b', color: palette.ink, fontSize: 34, opacity: semanticReveal(progress, index, 3), transform: `translateY(${(1 - inAt(progress, .08 + index * .27, .23 + index * .27)) * 34}px)`}}>{label}</div>)}</div><div style={{position: 'absolute', left: 150, top: 780, width: `${inAt(progress, .7, .96) * 1320}px`, height: 7, background: palette.coral}} /></>;
}
function FinalSynthesis({data, progress, stateCount}: {data: MemoryLabProps; progress: number; stateCount: number}) {const labels = labelsFor(data); return <><Title left={280} top={170} width={1360} size={82} align="center">{data.visualThesis}</Title><div style={{position: 'absolute', left: 190, top: 520, right: 190, display: 'grid', gridTemplateColumns: `repeat(${Math.max(1, labels.length)}, 1fr)`, gap: 28}}>{labels.map((label, index) => <div key={label} style={{height: 180, borderBottom: `6px solid ${index === labels.length - 1 ? palette.coral : palette.cyan}`, background: palette.panel, color: palette.ink, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 34, opacity: semanticReveal(progress, index, stateCount)}}>{label}</div>)}</div></>;}

export const MemoryLabEditorialScene = ({scene, assets}: {scene: SchemaScene; assets?: ResolvedAsset[]}) => {
  const data = propsOf(scene); if (!data) throw new Error(`${scene.id} 缺少 memoryLab renderer props`);
  const frame = useCurrentFrame(); const {fps} = useVideoConfig();
  const progress = interpolate(frame, [0, Math.max(1, scene.durationInFrames - 1)], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
  const absoluteSec = scene.start + frame / fps;
  const stateCount = semanticStateCountForDuration(scene.duration);
  const outroOpacity = scene.transitionOut === 'fade-out' ? interpolate(frame, [Math.max(0, scene.durationInFrames - fps * 5), scene.durationInFrames - 1], [1, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}) : 1;
  const boundAsset = assets?.[0];
  const asset = scene.id === 'S079' ? undefined : boundAsset;
  const drmDemonstration = data.sequence?.id === 'drm-mechanisms' && ['S035', 'S036', 'S037', 'S038'].includes(scene.id);
  const sequenceFocus = Boolean(data.sequence && data.sequence.id !== 'opening-disagreement' && data.sequence.phase > 0 && (scene.duration >= 7 || data.sequence.phase % 3 === 2) && data.family !== 'EVIDENCE_ARCHIVE' && data.family !== 'CHAPTER_INTERSTITIAL' && !asset && !drmDemonstration);
  const sequenceContent = data.sequence && data.family !== 'EVIDENCE_ARCHIVE' && data.family !== 'CHAPTER_INTERSTITIAL' && !asset && !sequenceFocus ? <SequenceWorld data={data} scene={scene} progress={progress} stateCount={stateCount} absoluteSec={absoluteSec} /> : null;
  const familyContent = data.family === 'KINETIC_CLAIM' ? <KineticClaim data={data} progress={progress} stateCount={stateCount} /> : data.family === 'VERSION_DIFF' ? <VersionDiff data={data} progress={progress} stateCount={stateCount} /> : data.family === 'PROCESS_MAP' ? <ProcessMap data={data} progress={progress} stateCount={stateCount} /> : data.family === 'TIMELINE' ? <Timeline data={data} progress={progress} stateCount={stateCount} /> : data.family === 'EVIDENCE_ARCHIVE' ? <EvidenceArchive data={data} scene={scene} progress={progress} asset={asset} /> : data.family === 'CONCEPT_SPACE' ? <ConceptSpace data={data} progress={progress} stateCount={stateCount} /> : data.family === 'COMPARISON' ? <Comparison data={data} progress={progress} stateCount={stateCount} /> : data.family === 'CHAPTER_INTERSTITIAL' ? <ChapterInterstitial data={data} scene={scene} progress={progress} /> : <FinalSynthesis data={data} progress={progress} stateCount={stateCount} />;
  const contextualAttribution = scene.id === 'S078' ? 'St. Louis Police Lantern Slides / DPLA · 无已知版权限制' : asset?.attribution || asset?.description;
  const contextualAnnotation = scene.id === 'S098' ? <div style={{position: 'absolute', right: 70, top: 700, width: 790, padding: '18px 22px', background: '#172225e8', borderLeft: `5px solid ${palette.coral}`, fontSize: 28, fontWeight: 650}}>真实家庭故事 → 研究者加入的虚构事件</div> : null;
  const contextualArchive = asset?.mediaType === 'image' && data.family !== 'EVIDENCE_ARCHIVE' ? <><Img src={staticFile(asset.publicPath)} style={{position: 'absolute', right: -20, top: 75, width: 1110, height: 820, objectFit: 'cover', opacity: .62, scale: interpolate(progress, [0, .38, .72, 1], [1.01, 1.09, 1.09, 1.02]), filter: 'grayscale(.78) contrast(.94)'}} /><div style={{position: 'absolute', inset: 0, background: 'linear-gradient(90deg, transparent 42%, #10161922 62%, #10161988 100%)'}} />{contextualAnnotation}<div style={{position: 'absolute', right: 70, top: 790, maxWidth: 880, padding: '14px 18px', color: palette.ink, background: '#172225e8', borderLeft: `5px solid ${palette.cyan}`, fontSize: 25, fontWeight: 650, opacity: semanticReveal(progress, 1, 3)}}>{data.archiveDisclosure || '背景资料 · 非研究现场'}</div><div style={{position: 'absolute', right: 70, top: 855, color: palette.muted, fontSize: 17, opacity: semanticReveal(progress, 2, 3)}}>{contextualAttribution}</div></> : null;
  const showSceneId = data.debugOverlay === true || data.showSceneId === true;
  return <AbsoluteFill style={{backgroundColor: chapterBackground[scene.chapter] ?? palette.bg, color: palette.ink, fontFamily, overflow: 'hidden', opacity: outroOpacity}}><div style={{position: 'absolute', inset: 0, background: 'radial-gradient(circle at 72% 28%, #31494b22, transparent 38%)'}} /><Meta data={data} scene={scene} />{sequenceContent ?? familyContent}{sequenceFocus && data.sequence ? <SequenceSpine sequence={data.sequence} /> : null}{contextualArchive}{showSceneId ? <div data-memory-lab-scene-id={scene.id} style={{position: 'absolute', right: 70, bottom: safeBottom, color: palette.coral, fontSize: 18}}>{scene.id}</div> : null}</AbsoluteFill>;
};
